services:
  postgres:
    image: postgres:17
    container_name: banking-postgres
    environment:
      POSTGRES_DB: banking
      POSTGRES_USER: banking
      POSTGRES_PASSWORD: banking
    ports:
      - "5432:5432"
    volumes:
      - banking_postgres_data:/var/lib/postgresql/data

volumes:
  banking_postgres_data: