spring.application.name=banking-transaction-service

spring.datasource.url=jdbc:postgresql://localhost:5432/banking
spring.datasource.username=banking
spring.datasource.password=banking

spring.jpa.hibernate.ddl-auto=validate
spring.jpa.show-sql=true