spring.application.name=banking-transaction-service

spring.datasource.url=jdbc:postgresql://localhost:5432/banking
spring.datasource.username=banking
spring.datasource.password=banking

spring.jpa.hibernate.ddl-auto=validate

spring.jpa.show-sql=true
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.orm.jdbc.bind=TRACE

spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=${MAIL_USERNAME}
spring.mail.password=${MAIL_PASSWORD}

spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true