CREATE TABLE account
(
    id               BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    owner_name       VARCHAR(150)             NOT NULL,

    account_number   VARCHAR(50)              NOT NULL UNIQUE,

    balance          NUMERIC(19, 2)           NOT NULL DEFAULT 0
        CHECK (balance >= 0),

    reserved_balance NUMERIC(19, 2)           NOT NULL DEFAULT 0
        CHECK (reserved_balance >= 0),

    version          BIGINT                   NOT NULL DEFAULT 0,

    status           VARCHAR(20)              NOT NULL DEFAULT 'ACTIVE'
        CHECK (status IN ('ACTIVE', 'BLOCKED', 'CLOSED')),

    created_at       TIMESTAMP WITH TIME ZONE NOT NULL,

    updated_at       TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT chk_account_reserved_balance
        CHECK (reserved_balance <= balance)
);

CREATE TABLE transfer
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    reference              VARCHAR(100)             NOT NULL UNIQUE,

    source_account_id      BIGINT                   NOT NULL,

    destination_account_id BIGINT                   NOT NULL,

    amount                 NUMERIC(19, 2)           NOT NULL
        CHECK (amount > 0),

    status                 VARCHAR(20)              NOT NULL DEFAULT 'PENDING'
        CHECK (status IN ('PENDING', 'COMPLETED', 'FAILED')),

    created_at             TIMESTAMP WITH TIME ZONE NOT NULL,

    updated_at             TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_transfer_source_account
        FOREIGN KEY (source_account_id)
            REFERENCES account (id),

    CONSTRAINT fk_transfer_destination_account
        FOREIGN KEY (destination_account_id)
            REFERENCES account (id),

    CONSTRAINT chk_transfer_different_accounts
        CHECK (source_account_id <> destination_account_id)
);

CREATE TABLE ledger_entry
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    transfer_id BIGINT                   NOT NULL,

    account_id  BIGINT                   NOT NULL,

    type        VARCHAR(10)              NOT NULL
        CHECK (type IN ('DEBIT', 'CREDIT')),

    amount      NUMERIC(19, 2)           NOT NULL
        CHECK (amount > 0),

    created_at  TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT fk_ledger_transfer
        FOREIGN KEY (transfer_id)
            REFERENCES transfer (id),

    CONSTRAINT fk_ledger_account
        FOREIGN KEY (account_id)
            REFERENCES account (id)
);

CREATE TABLE audit_log
(
    id         BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    action     VARCHAR(50)              NOT NULL,

    reference  VARCHAR(100),

    status     VARCHAR(20),

    message    VARCHAR(500),

    created_at TIMESTAMP WITH TIME ZONE NOT NULL
);

CREATE INDEX idx_audit_log_reference
    ON audit_log (reference);

CREATE INDEX idx_ledger_entry_account_created
    ON ledger_entry(account_id, created_at DESC);

CREATE INDEX idx_ledger_entry_transfer
    ON ledger_entry(transfer_id);