CREATE TABLE idempotency_record
(
    id                  BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    idempotency_key     VARCHAR(100) NOT NULL,
    request_fingerprint VARCHAR(64) NOT NULL,
    status              VARCHAR(20) NOT NULL,
    transfer_reference  VARCHAR(100),
    created_at          TIMESTAMP WITH TIME ZONE NOT NULL,
    updated_at          TIMESTAMP WITH TIME ZONE NOT NULL,

    CONSTRAINT uq_idempotency_key
        UNIQUE (idempotency_key),

    CONSTRAINT chk_idempotency_status
        CHECK (status IN ('PROCESSING', 'COMPLETED', 'FAILED'))
);