CREATE TABLE outbox_event
(
    id              BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    event_type      VARCHAR(100) NOT NULL,

    aggregate_type  VARCHAR(50) NOT NULL,

    aggregate_id    VARCHAR(100) NOT NULL,

    payload         TEXT NOT NULL,

    status          VARCHAR(20) NOT NULL DEFAULT 'PENDING',

    attempts        INTEGER NOT NULL DEFAULT 0,

    locked_by VARCHAR(100),

    locked_at TIMESTAMP WITH TIME ZONE,

    created_at      TIMESTAMP WITH TIME ZONE NOT NULL,

    processed_at    TIMESTAMP WITH TIME ZONE
);